version: 3

tasks:
  dev:
    desc: Run dev server.
    cmds:
      - npm run dev

  publish-to-github:
    desc: Publish documentation site to GitHub.
    cmds:
      - npm run deploy

  publish-to-npmjs:
    desc: Publish package to npmjs.
    cmds:
      - npm publish
